[package]

name = "cas"
version = "0.1.1"
authors = [ "David Brown <davidb@davidb.org>" ]
license = "MIT"
description = """
Content Addressable Store
"""

[dependencies]
byteorder = "*"
libc = "*"
rustc-serialize = "*"
flate2 = "*"

# This is a testing dependency.
tempdir = "*"
rand = "*"
